name: Python CI/CD

on:
  push:
    branches: [main]
    paths:
      - "basic-ci/**"
  pull_request:
    branches: [main]
    paths:
      - "basic-ci/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to"
        required: false
        default: "dev"
      version:
        description: "Version to deploy"
        required: false
        default: "latest"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: basic-ci

    steps:
      - uses: actions/checkout@v2

      - name: Install Pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV

      - name: Install Python version from Poetry
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          pyenv install $(poetry env info --path | grep -o '[0-9]\.[0-9]\.[0-9]') -s  # Install the required Python version
          pyenv global $(poetry env info --path | grep -o '[0-9]\.[0-9]\.[0-9]')    # Set the global Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Use correct Python version from Poetry
        run: |
          cd ${{ env.PROJECT_DIR }}
          poetry env use python3

      - name: Install dependencies (dev)
        run: |
          cd ${{ env.PROJECT_DIR }}
          poetry install

      - name: Run tests and collect coverage
        run: |
          cd ${{ env.PROJECT_DIR }}
          poetry run pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ env.PROJECT_DIR }}
          file: ${{ env.PROJECT_DIR }}/coverage.xml
          name: ${{ env.PROJECT_DIR }}-coverage-report

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      PROJECT_DIR: basic-ci

    steps:
      - uses: actions/checkout@v2

      - name: Install Pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV

      - name: Install Python version from Poetry
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          pyenv install $(poetry env info --path | grep -o '[0-9]\.[0-9]\.[0-9]') -s  # Install the required Python version
          pyenv global $(poetry env info --path | grep -o '[0-9]\.[0-9]\.[0-9]')    # Set the global Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Use correct Python version from Poetry
        run: |
          cd ${{ env.PROJECT_DIR }}
          poetry env use python3

      - name: Install production dependencies
        run: |
          cd ${{ env.PROJECT_DIR }}
          poetry install --no-dev

      - name: Deploy application
        run: |
          cd ${{ env.PROJECT_DIR }}
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment"
